name: Tests
on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint --max-warnings=0
      - name: Type check
        run: pnpm typecheck
      - name: Build Plugin
        run: pnpm build
      - name: Build demo
        run: pnpm build:demo
      - name: Integration tests
        run: pnpm test:int
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: E2E tests
        run: pnpm test:e2e